i3blocks:
  wifi:
    - NetworkManager (nmcli, nmtui)
  temperature:
    - sensors
  bluetooth:
    - bluez
    - blueberry
  brightness:
    - light
    - bc
  cpu_usage:
    - sysstat
  battery:
    - acpi
  playerctl:
    - playerctl
  window:
    - xdotool
  weather:
    - wget
  
i3:
  - i3blocks
  - compton
  - dmenu
  - quickswitch-i3
  - xfce4-appfinder (appmenu)
  - nitrogen (wallpaper)
  - xfce4-notifyd (system notification)
  - lxappearance-gtk3
  - arandr

DM:
  - lightdm
  - lightdm-gtk-greeter
  - light-locker
 
clipboard:
  - xfce4-clipman-plugin

power saving:
  - xfce4-power-manager

other apps:
  - deepin-screenshot
  - nemo[gvfs-smb(samba客户端),nemo-fileroller,nemo-image-converter,nemo-preview]
  - fcitx
  - google-chrome
  - telegram-desktop
  - pantheon-terminal
  - shotwell (image)
  - vlc (video)
  - netease-cloud-music (music)
  - file-roller
  - visual-studio-code

fonts:
  - Titillium
  - fontawesome5
  - Roboto mono
  - wqy-microhei
  - Source Han Sans CN


find WM: xprop|grep WM_CLASS